### ISSUE TITLE
Stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by anton-darahakupets-epam** [Cognifide/bobcat#133]
12:16:00.101 INFO - Executing: [find element: By.xpath: //div[contains(@id, 'ext-comp-') and contains(@style, 'display: block') and contains(@style, 'visibility: visible')]//div[contains(@class, 'x-window-footer')]//button[text()='OK']])
12:16:00.115 INFO - Done: [find element: By.xpath: //div[contains(@id, 'ext-comp-') and contains(@style, 'display: block') and contains(@style, 'visibility: visible')]//div[contains(@class, 'x-window-footer')]//button[text()='OK']]
12:16:00.125 INFO - Executing: [implicit wait: 1000])
12:16:00.127 INFO - Done: [implicit wait: 1000]
12:16:00.132 INFO - Executing: [click: 54 [[ChromeDriver: chrome on XP (4ff171e97d5b794417dfd920aa033cb6)] -> xpath: //div[contains(@id, 'ext-comp-') and contains(@style, 'display: block') and contains(@style, 'visibility: visible')]//div[contains(@class, 'x-window-footer')]//button[text()='OK']]])
12:16:00.206 INFO - Done: [click: 54 [[ChromeDriver: chrome on XP (4ff171e97d5b794417dfd920aa033cb6)] -> xpath: //div[contains(@id, 'ext-comp-') and contains(@style, 'display: block') and contains(@style, 'visibility: visible')]//div[contains(@class, 'x-window-footer')]//button[text()='OK']]]
12:16:00.215 INFO - Executing: [is displayed: 54 [[ChromeDriver: chrome on XP (4ff171e97d5b794417dfd920aa033cb6)] -> xpath: //div[contains(@id, 'ext-comp-') and contains(@style, 'display: block') and contains(@style, 'visibility: visible')]//div[contains(@class, 'x-window-footer')]//button[text()='OK']]])
12:16:00.226 INFO - Done: [is displayed: 54 [[ChromeDriver: chrome on XP (4ff171e97d5b794417dfd920aa033cb6)] -> xpath: //div[contains(@id, 'ext-comp-') and contains(@style, 'display: block') and contains(@style, 'visibility: visible')]//div[contains(@class, 'x-window-footer')]//button[text()='OK']]]
12:16:02.237 INFO - Executing: [click: 54 [[ChromeDriver: chrome on XP (4ff171e97d5b794417dfd920aa033cb6)] -> xpath: //div[contains(@id, 'ext-comp-') and contains(@style, 'display: block') and contains(@style, 'visibility: visible')]//div[contains(@class, 'x-window-footer')]//button[text()='OK']]])
12:16:02.713 WARN - Exception thrown
org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=54.0.2840.99)
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 10.0.10586 x86_64) (WARNING: The server did not provide any stacktrace information)

What is the reason that an exception is thrown?
This exception is thrown in all test cases provided within Bobcat AEM JUnit archetype.
You can see from the logs the Bobcat tries to click "OK" dialog button two times, what is the reason of this behavior?

**Comment by kkarolk** [comment]
Hi Anton, could you provide java stacktrace from the moment of failure?

**Comment by anton-darahakupets-epam** [comment]
Please see [error-log.txt](https://github.com/Cognifide/bobcat/files/648829/error-log.txt).

By the end of the tests execution it says me that test result is OK,
but the existence of this exceptions has put into question this result.

**Comment by kkarolk** [comment]
We will look at this, thanks

**Comment by mmanski** [comment]
Hey Anton,
Unfortunately our integration tests don't show any problems with the mentioned archetype. You should bear in mind that AEM 6.1 is the preferred version to run example tests, could you let us now on what AEM version you are trying to execute these tests?
