### ISSUE TITLE
JUnit 5 support

### ISSUE THREAD

**Issue by toniedzwiedz** [Cognifide/bobcat#153]
The GA release of JUnit 5 [is due later this year](https://github.com/junit-team/junit5/wiki/Roadmap). It would be nice to support it when it launches.

Among other things, JUnit 5 introduces a [new, more flexible extension model](http://junit.org/junit5/docs/current/user-guide/#extensions) that could be of interest to the Bobcat team.

Expected deliverables:
- make sure Bobcat can be used with JUnit 5
- document JUnit 5 compatibility

Please mind that this will probably require a major version release.

**Comment by mkrzyzanowski** [comment]
Released in 1.5.0

**Comment by toniedzwiedz** [comment]
Nice :)
