### ISSUE TITLE
Touch UI set Field RichText 

### ISSUE THREAD

**Issue by oliver2202** [Cognifide/bobcat#159]
using the `sling:resourceType="cq/gui/components/authoring/dialog/richtext`  we aren't able to set the value

```
page.getParsys(parsys).getComponent(COMPONENT_NAME)
				.openDialog()
				.setField("Block 1", FieldType.RICHTEXT.name(), "test test test")
				.confirm();
```

below the error

> Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":".coral-RichText"}
>   (Session info: chrome=57.0.2987.98)
>   (Driver info: chromedriver=2.28.455520 (cc17746adff54984afff480136733114c6b3704b),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
> Command duration or timeout: 15.01 seconds
> For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html

**Comment by mmanski** [comment]
Hi,
Unfortunately, the "cq/gui/components/authoring/dialog/richtext" is not supported by default. RichText in Bobcat is basing on "foundation/components/text". You can always extend this functionality by providing you own component description as descibed here: https://github.com/Cognifide/bobcat/wiki/Component-descriptions
