### ISSUE TITLE
Touch UI siteadmin provides support only for admin user

### ISSUE THREAD

**Issue by mmanski** [Cognifide/bobcat#182]
When using Siteadmin functionality provided by Bobcat 1.2.0 on AEM 6.2 SP1 CFP1 on different account than an admin multiple errors occur. It seems like some modals and dialogs have slightly modified markup

**Comment by mmanski** [comment]
This can be easily tested by running siteadmin test on a user that is not an admin. As far as I remember confirmation modal after page creation had different markup for example.

**Comment by mkrzyzanowski** [comment]
Will be addressed in new authoring API.
