### ISSUE TITLE
acceptInsecureCerts capability

### ISSUE THREAD

**Issue by F3Ni0** [Cognifide/bobcat#190]
Hi,

I upgraded framework to 1.2.1 version and I tried to use **acceptInsecureCerts** desired capability.
How did I do that? In **webdriver.properties** file I added **webdriver.cap.acceptInsecureCerts=true**

However, I got an error 
`11:17:39.162 [Forwarding newSession on session null to remote] DEBUG org.apache.http.wire - http-outgoing-16 << "{"value":{"error":"invalid argument","message":"acceptInsecureCerts was not a boolean",
"stacktrace":"stack backtrace:\n   0:           0x489f6f - <no info>\n   1:           0x48ad59 - <no info>\n   2:           0x437561 - <no info>\n   3:           0x43ad25 - <no info>\n   4:           
0x443f9a - <no info>\n   5:           0x41ddb1 - <no info>\n   6:           0x4091c7 - <no info>\n   7:           0x6bc939 - <no info>\n   8:           0x415a19 - <no info>\n   9:           0x6b6e43 -
 <no info>\n  10:         0x776f59cd - BaseThreadInitThunk"}}"`

acceptInsecureCerts was not a boolean. Is there anything wrong with the way I used it or is there any problem with properties parser?

**Comment by Shaihuludus** [comment]
There is a bug in properties parser, It treats all caps as Strings

**Comment by Shaihuludus** [comment]
Problem fixed and waiting for release

**Comment by mkrzyzanowski** [comment]
Released in 1.3.0
