### ISSUE TITLE
HTTP Session output - Question

### ISSUE THREAD

**Issue by F3Ni0** [Cognifide/bobcat#196]
Hi,

I use bobcat-aem archetype. Every test creates an output in console from HTTP sessions like this:
`10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-1325: set socket timeout 
to 10800000
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.impl.execchain.MainClientExec - Executing request POST /session/e483f3f074cf9e69b0b44b
98b62bf034/element HTTP/1.1
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.headers - http-outgoing-1325 >> POST /session/e483f3f074cf9e69b0b44b98b62bf034/element
 HTTP/1.1
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.headers - http-outgoing-1325 >> Content-Type: application/json; charset=utf-8
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.headers - http-outgoing-1325 >> Content-Length: 32
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.headers - http-outgoing-1325 >> Host: localhost:45718
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.headers - http-outgoing-1325 >> Connection: Keep-Alive
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.headers - http-outgoing-1325 >> User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_111)
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.headers - http-outgoing-1325 >> Accept-Encoding: gzip,deflate
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.wire - http-outgoing-1325 >> "POST /session/e483f3f074cf9e69b0b44b98b62bf034/element H
TTP/1.1[\r][\n]"
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.wire - http-outgoing-1325 >> "Content-Type: application/json; charset=utf-8[\r][\n]"
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.wire - http-outgoing-1325 >> "Content-Length: 32[\r][\n]"
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.wire - http-outgoing-1325 >> "Host: localhost:45718[\r][\n]"
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.wire - http-outgoing-1325 >> "Connection: Keep-Alive[\r][\n]"
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.wire - http-outgoing-1325 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_111)[\r]
[\n]"
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.wire - http-outgoing-1325 >> "Accept-Encoding: gzip,deflate[\r][\n]"
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.wire - http-outgoing-1325 >> "[\r][\n]"
10:21:08.188 [Forwarding findElement on session e483f3f074cf9e69b0b44b98b62bf034 to remote] DEBUG org.apache.http.wire - http-outgoing-1325 >> "{"using":"xpath","value":".//*"}"`

How do I turn this off?

**Comment by mkrzyzanowski** [comment]
Hi @F3Ni0,

the issue mentioned above has been fixed in the latest version of our archetypes. You can easily fix it by adding following configuration file to your project: https://github.com/Cognifide/bobcat-aem-integration-tests/blob/master/src/test/resources/logback-test.xml
