### ISSUE TITLE
[HELP] archetype for bb-cumber

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat#199]
Creating new repo with bb-cumber; need a sample repo to start with

**Comment by mkrzyzanowski** [comment]
Hi, @DeChrish!

After generating a project from one of following archetypes:
https://github.com/Cognifide/bobcat-archetype-bdd
https://github.com/Cognifide/bobcat-archetype-aem-bdd
you will end up with some sample tests using the `bb-cumber` module. 

For additional information, please refer to our Wiki: https://github.com/Cognifide/bobcat/wiki
