### ISSUE TITLE
Question: Sample code snippet to switch from Edit to Preview mode

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat#201]
After Authoring the component, we need to switch to Preview mode for On Click action. Any helper function is available in bobcat?

**Comment by kkarolk** [comment]
Hi @DeChrish 

Thanks for your question. 
Such helper is available in Bobcat. Please have a look at GlobalBar#switchToPreviewMode: https://github.com/Cognifide/bobcat/blob/master/bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/pageobjects/touchui/GlobalBar.java

Example usage: https://github.com/Cognifide/bobcat/blob/master/bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/pageobjects/pages/AuthorPage.java
