### ISSUE TITLE
Add cucumber-jvm-parallel-plugin as a default way for running tests in parallel in BDD templates

### ISSUE THREAD

**Issue by mkrzyzanowski** [Cognifide/bobcat#209]
- add a basic configuration for https://github.com/temyers/cucumber-jvm-parallel-plugin in BDD archetypes 
- document this approach on Bobcat Wiki

**Comment by DeChrish** [comment]
@mkrzyzanowski  below plugin looks promising, my 2 cents; https://github.com/trivago/cucable-plugin

**Comment by mkrzyzanowski** [comment]
@Shaihuludus, the above needs to be revisited since we are moving to Gradle.

**Comment by mkrzyzanowski** [comment]
TODO: provide a viable Gradle alternative

**Comment by DeChrish** [comment]
@kaczymuczy  Cucumber ver 4.x allows us to run the test in parallel.
sample :  https://github.com/abhishek8908/cucumber-v4-example

**Comment by mkrzyzanowski** [comment]
As mentioned above, Cucumber provides the support OOTB - please follow the #309 for further update.
