### ISSUE TITLE
component node naming convention

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat#212]
Currently node is named as `link-image-text` . aem author automatically converts the component locator to `link_image_text` and if it added twice the random number is appends to  `link_image_text`. 

The current normalize implantation ignore alpha-numeric after `_` , which is not helpful to insert components named like above example.

```
 public static String normalize(String dataPath) {
    return Character.isDigit(dataPath.charAt(dataPath.length() - 1)) ?
        StringUtils.substringBeforeLast(dataPath, "_") :
        dataPath;
  }
```

**Comment by mkrzyzanowski** [comment]
The normalization is done only when it is a duplicate and the random number is added to given node, e.g.:
- `link_image_text` will not be processed
- `link_image_text_2343423`  will become a `link_image_text`
