### ISSUE TITLE
[HELP] Drag And Drop within frames

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat#214]
Working in image drag and drop.

In my current author DOM, I don't see any iframe; how to create a component with draggable and droppable without frame-path?

**Comment by mkrzyzanowski** [comment]
Hi @DeChrish,

you can pass the FramePath matching the main window like this:

```
@Inject
DragAndDropFactory factory;

...

Draggable yourDraggableElement = factory.createDraggable(yourWebelement, FramePath.parsePath("/"));

Droppable yourDroppableElement = factory.createDroppable(yourOtherElement, FramePath.parsePath("/"));
```

I guess methods in the `DragAndDropFactory` with the default pre-set would come in handy ;)
