### ISSUE TITLE
brining bobcat to JS

### ISSUE THREAD

**Issue by bharathram89** [Cognifide/bobcat#216]
Hi All,

Im trying to see if its possible to use the AEM features of bobcat into a JS node framework Im using. I have tried to just use the jar and create an instance of the aemLogin page and tried to access the login methods but was not very successful. I was wondering if this was even possible any suggestion would help.

Thank you
Bharath Ram

**Comment by mkrzyzanowski** [comment]
Hi @bharathram89, unfortunately Bobcat requires proper initialization as it does a lot in the background - it is not possible to the JAR and reuse parts of Page Objects.
