### ISSUE TITLE
InsertComponentWindow - add component based on Group

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat#217]
AEM Classic implementation has an option to add the component from the group. But in the touch UI implementation, i could not find an option to include it.

Currently, we have the same component name in two different group.
`page.addComponent(parsys, "Text");`
The above method is not helpful. Any advice?

**Comment by mkrzyzanowski** [comment]
Hi @DeChrish,

sorry for the late response. The current implementation grabs the first component in the Insert Window that matches the provided name. Unfortunately, the current implementation does not allow extending it easily or swapping some implementation parts. At the moment you would need to write your own `InsertComponentWindow` with the added functionality to respect the group while locating the component and `Parsys` that uses this custom implementation.

It is definitely a valid improvement for future versions.

**Comment by mkrzyzanowski** [comment]
It will be addressed in the new authoring API in BB 2.0
