### ISSUE TITLE
[HELP] - Unable to read component dialog fields without parsys parameter on page.configureComponent

### ISSUE THREAD

**Issue by ganesh25403** [Cognifide/bobcat#219]
@marcinczeczko

- We dont have parsys in our AEM template. All the components are pre-defined in a template. 
- We are trying to read values from component dialog. 
- When we try to use "page.configureComponent", this method expect a parsys as mandatory parameter.

**Question?**

Could you please let us know if any alternate way to read touch UI dialog fields using yaml file? I could not find a documentation surrounding this. Could you please guide us in the right direction?

**Comment by mkrzyzanowski** [comment]
Hi @ganesh25403,

without a parsys, you have to reference the component directly. In this situation you can re-use the code from the [Parsys](https://github.com/Cognifide/bobcat/blob/fd14c7c535c7c8e9fb5664d87dfc3f8f446435e4/bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/pageobjects/touchui/Parsys.java) class:

1. You need your own version of AuthorPage - create one and add there the following fields:

```
  @Inject
  private Components componentsData;

  @FindPageObject
  private List<Component> components;
```

2. Now, you can query the list to locate your component with the following method (similar to [this](https://github.com/Cognifide/bobcat/blob/fd14c7c535c7c8e9fb5664d87dfc3f8f446435e4/bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/pageobjects/touchui/Parsys.java#L116) method):

```
public Component getComponent(String componentName) {
    String dataPath = componentsData.getDataPath(componentName);
    String componentDataPath = DataPathUtil.normalize(dataPath);
    return componentList.stream() //
        .filter(containsDataPath(componentDataPath)) //
        .findFirst() //
        .orElseThrow(() -> new IllegalStateException("Component not found: " + componentName));
}

private Predicate<Component> containsDataPath(String componentDataPath) {
  return component -> StringUtils.contains(component.getDataPath(), componentDataPath);
}
```

This will allow you to configure that particular component :).

**Comment by ganesh25403** [comment]
Hi @marcinczeczko,

I tried to override the AuthorPage and created custom class. I have an issue now with AuthorPageFactory is creating instance of AuthorPage, I could not typecast AuthorPage to Custom class. I could not able to use my custom author page class.

public class ArticlePromo {

    @Inject
    private SiteAdminPage siteAdminPage;

    @Inject
    private Pages pages;

    @Inject
    private AuthorPageFactory authorPageFactory;


    private ProviderAuthorPage page;
    //private ProviderAuthorPage providerAuthorPage;

    private String parsys;


    private static final String CONFIGURATION = "Article Promo Component";

    private static final String COMPONENT_NAME = "Article Promo";

    @Then("^I configure Article Promo Component$")
    public void iConfigureArticlePromoComponent() {
            page = (ProviderAuthorPage) authorPageFactory.create(pages.getPath(CONFIGURATION));
            page.open();
            page.isLoaded();
            parsys = pages.getParsys(CONFIGURATION);
            System.out.println(parsys);
            page.addComponent(parsys, COMPONENT_NAME);
            page.open();
            page.configureComponent(parsys, COMPONENT_NAME, "article_promo");
        }
}

**Error:**
java.lang.ClassCastException: com.cognifide.qa.bb.aem.touch.pageobjects.pages.AuthorPage$$EnhancerByGuice$$bbeb1672 cannot be cast to bobcat.pageobject.ProviderAuthorPage  at bobcat.author.component.ArticlePromo.iConfigureArticlePromoComponent(ArticlePromo.java:44)
  at ✽.Then I configure Article Promo Component(articlePromo.feature:6

Could you please suggest a way to do this?

**Comment by mkrzyzanowski** [comment]
The factory you are using was configured to return the `AuthorPage` from Bobcat. If you would like to use the factory for your own implementation, then you need to configure a new one.

You can do it the same way as we do in Bobcat:
- create your own [AuthorPageFactory] interface, similar to the one in Bobcat: [link](https://github.com/Cognifide/bobcat/blob/a54cf837f0699edf6f607f39f610c500ae2a5c23/bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/pageobjects/pages/AuthorPageFactory.java)
- configure it in your Guice module, in a similar way to how we do it: [link](https://github.com/Cognifide/bobcat/blob/a54cf837f0699edf6f607f39f610c500ae2a5c23/bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/modules/AemTouchUiModule.java#L49)

After that, you should be all set :).

**Comment by mkrzyzanowski** [comment]
Closing the issue. If you have any further questions, please let us know.
