### ISSUE TITLE
Implement Subreport functionality

### ISSUE THREAD

**Issue by mmanski** [Cognifide/bobcat#22]
There is a problem with revealing a subreport form report. When clicking on "+" sign console error shows "togglePart is undefined". It looks like this method is not implemented at all. We need to implement it and investigate the json structure of subreport as for now it is not very handy.

**Comment by Shaihuludus** [comment]
We need a design session for this feature. Simple adding js is not enough

**Comment by mkrzyzanowski** [comment]
We're going to revamp reporting module, n/a now.
