### ISSUE TITLE
Wiki Links For Archetypes in "Getting Started" Are Incorrect

### ISSUE THREAD

**Issue by rainrivas** [Cognifide/bobcat#220]
Need to remove the brackets from table...

Archetypes | Description
-- | --
[[Bobcat JUnit | https://github.com/cogbobcat/bobcat-archetype]]
[[Bobcat BDD | https://github.com/cogbobcat/bobcat-archetype-bdd]]
[[Bobcat AEM JUnit | https://github.com/cogbobcat/bobcat-archetype-aem]]
[[Bobcat AEM BDD | https://github.com/cogbobcat/bobcat-archetype-aem-bdd]]
[[Bobcat Appium | https://github.com/Cognifide/bobcat-archetype-appium]]

**Comment by mkrzyzanowski** [comment]
Thanks a lot! Fixed :)
