### ISSUE TITLE
[HELP] Component configuration for multifield in dialog. 

### ISSUE THREAD

**Issue by purubarh** [Cognifide/bobcat#222]
@CognifideLabs @mmajchrzak @mchrominski 
There is a component which has one Tab<ABC> and Which has one Text field<Text> and Multifield<Slides>. Further once click on Add click, there are fields such as text fields and drop down. As per Wiki, I have tried with YAML file as below:

![image](https://user-images.githubusercontent.com/15006279/35409234-75d1887e-01c6-11e8-9e05-7b2b6e10db4e.png)

When trying to run, it throwing error which is as follows:

![image](https://user-images.githubusercontent.com/15006279/35409288-982d917e-01c6-11e8-8e7e-bc2faf46c74c.png)
Help Appreciated.

**Comment by mkrzyzanowski** [comment]
Your YAML file seems to be incorrect: you have `-item:` instead of `- item:`. That lack of space causes the deserialization errors, YAML are sensitive like that ;)
