### ISSUE TITLE
Bobcat AEM-BDD install initialization error

### ISSUE THREAD

**Issue by thirunavookkarasu** [Cognifide/bobcat#225]
I followed bobcat AEM-BDD installation steps for Hello world program. I followed the same in Mac OS. After successful installation, I run the "MVN CLEAN INSTALL" command from HelloWorld folder and it throws the Initialization error. How to run the HelloWorld program for AEM-BDD Archtype.

**Comment by discovermoi** [comment]
Hi Thiru, Did you get an answer?

**Comment by mkrzyzanowski** [comment]
Hi @thirunavookkarasu!
I'm closing the ticket for now. If the issue is still valid, please provide more info according to our latest [issue template](https://github.com/Cognifide/bobcat/blob/master/.github/ISSUE_TEMPLATE.md) and reopen it,
