### ISSUE TITLE
getParsys for a Parsys inside Multiple parsys

### ISSUE THREAD

**Issue by thirunavookkarasu** [Cognifide/bobcat#226]
datapath for a parsys looks like .....jcr: content/content/cardsv2/carditem/carditem/minicarditem. How to edit the parsys with such a long datapath as it is inside multiple parsys. When I tried with getParsys (Configuration), where the Configuration in the Pages.YAML has the value like datapth: /content/cardsv2/carditem/carditem/minicarditem - throwing Null pointer exception.

**Comment by mkrzyzanowski** [comment]
Hi @thirunavookkarasu,

there's not enough info for me to answer the above question.
How are you accessing the parsys? Could you provide the full stacktrace?

Also, please note that when I wrote the TouchUI bits, I did not have complex cases like nested parsyses in mind, so it is possible that it won't be possible with current API and some additional development would be required.

**Comment by mkrzyzanowski** [comment]
Nested parsyses will be addressed in the upcoming new authoring API.
