### ISSUE TITLE
Code cleanup - mark features which will be abandoned with @Deprecated

### ISSUE THREAD

**Issue by Shaihuludus** [Cognifide/bobcat#228]
Review the codebase and mark with `@Deprecated` functionality that will be removed.

- [x] Core
- [x] Annotations
- [x] JUnit
- [x] Email
- [x] Reports
- [x] Traffic
- [x] Cucumber
- [x] AEM Common
- [x] AEM ClassicUI
- [x] AEM TouchUI

**Comment by mkrzyzanowski** [comment]
h3. Core module
- `com.cognifide.qa.bb.loadable` package

**Comment by mkrzyzanowski** [comment]
Per #244, deprecate JUnit and Reports modules & update the documentation accordingly.

**Comment by mkrzyzanowski** [comment]
Deprecations:
- `bb-junit` module
- `bb-reports` module
- `bb-aem-classic` module
- `bb-aem-touch-ui` module
- `com.cognifide.qa.bb.qualifier.Retry` and whole retry mechanism (goes away with `bb-junit`)

**Comment by mkrzyzanowski** [comment]
Additional items for further cleanup:
- `BobcatWait`/`Conditions`/`WebElementUtils` rework: providing a single utility
- `WebDriverType` - move the proxy cookie to a modifier/remove it totally
- `PageObjectInjector` - add support for injections of PageObjects with locators in annotation

**Comment by mkrzyzanowski** [comment]
Released in `1.6.0`
