### ISSUE TITLE
Investigate problem with gray panel that pops up when scrolling by WebDriver on FF 24

### ISSUE THREAD

**Issue by mmanski** [Cognifide/bobcat#23]
Sometimes when WebDriver scrolls the page, a gray panel is appearing on the bottom. I'm assuming that this is a JS console that is used to scroll the window by some script

**Comment by kkarolk** [comment]
![2016-08-08_15h28_57](https://cloud.githubusercontent.com/assets/2323048/17481316/d4eeddc4-5d7c-11e6-9647-67d0fee0f25a.png)

**Comment by kkarolk** [comment]
Let's try to update firefox to version supported by AEM Touch UI:
https://docs.adobe.com/content/docs/en/aem/6-0/deploy/technical-requirements.html#Supported%20Browsers%20for%20Authoring%20User%20Interface
