### ISSUE TITLE
grapping session id from BrowserStack

### ISSUE THREAD

**Issue by reedsexpo** [Cognifide/bobcat#233]
# Environment

While running test in BrowserStack , I would want to print locally the session ID .

Browserstack  provided the code sniplet to be able to grap the session id as 
((RemoteWebDriver) driver).getSessionId();

In my Bobcat Framwork , If I tried to add that sniplet above it gives me an error 

Message: java.lang.ClassCastException: com.cognifide.qa.bb.provider.selenium.webdriver.close.ClosingAwareWebDriverWrapper cannot be cast to org.openqa.selenium.remote.RemoteWebDriver

can you please advice how I can do it , please kindly asking you if you can provde an example as well.

Thanks
Bob

**Comment by reedsexpo** [comment]
@mmajchrzak any response on this please ?

**Comment by mkrzyzanowski** [comment]
Hey @reedsexpo,

seems like you would like to access the RemoteWebDriver API, it's a bit tricky due to the casting fun you observed. Have you tried the method I suggested in one of your previous questions: https://github.com/Cognifide/bobcat/issues/215#issuecomment-351354417 ?

**Comment by mkrzyzanowski** [comment]
Saw your comment in the other issue, I guess we can consider this solved :)
