### ISSUE TITLE
Unable to write own test cases - local aem instance not recognized

### ISSUE THREAD

**Issue by discovermoi** [Cognifide/bobcat#236]
I tried implementing the login class that simply connects to the aem instance but no luck. I am getting null pointer exception. There is no preface for this help page https://github.com/Cognifide/bobcat/wiki/AEM-Login. It is very naive and does't cover the config part that is required.

I am using aem 6.2 and I am dying to put this framework to use for my own aem application. Timely help is highly appreciated.
[aem login test class in bobcat failing.pdf](https://github.com/Cognifide/bobcat/files/1936432/aem.login.test.class.in.bobcat.failing.pdf)

**Comment by mkrzyzanowski** [comment]
Closing, as we're solving it via email :).
