### ISSUE TITLE
Publish and Unpublish APIs not working for aem62

### ISSUE THREAD

**Issue by discovermoi** [Cognifide/bobcat#240]
Activate and deactivate page working perfectly in aem6.1. It in fact runs thru the create page dialog as well clearly.

But it is not working in aem 62.  seems stuck.

if this is a friendly framework for aem 62, It would be great to call it out now itself as we will moving to aem 64 sooner so that I will be able to find out an alternative else stop using the compiled classes and use the framework directly so that we get to fix it as we face issues while using it.

```
Error Stack org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"button[icon='globeStrike']"}
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.38.551581 (2c9c29527ada10af4745ab26dd000ebb6d5e055e),platform=Mac OS X 10.12.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'C02SNYAUGVC1', ip: '10.24.40.59', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_152'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.38.551581 (2c9c29527ada10..., userDataDir: /var/folders/gv/jdzvrj1j5cg...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 66.0.3359.139, webStorageEnabled: true}
Session ID: ab21eea294f22d84607e783a17d66c48
*** Element info: {Using=css selector, value=button[icon='globeStrike']}
```

**Comment by discovermoi** [comment]
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"button[icon='globeStrike']"}
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.38.551581 (2c9c29527ada10af4745ab26dd000ebb6d5e055e),platform=Mac OS X 10.12.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'C02SNYAUGVC1', ip: '10.24.40.59', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_152'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.38.551581 (2c9c29527ada10..., userDataDir: /var/folders/gv/jdzvrj1j5cg...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 66.0.3359.139, webStorageEnabled: true}
Session ID: ab21eea294f22d84607e783a17d66c48
*** Element info: {Using=css selector, value=button[icon='globeStrike']}

**Comment by mkrzyzanowski** [comment]
Closing this for now, in case of any further update/questions, let us know.
