### ISSUE TITLE
Code cleanup - review and update dependencies

### ISSUE THREAD

**Issue by mkrzyzanowski** [Cognifide/bobcat#243]
Currently, there's a small dependency hell in Bobcat. The scope of this task is to:
- review all dependencies across all modules
- decide whether some external libs should be replaced
- bump dependencies to their latest versions

## Core module
- [x] libs reviewed
- [x] dependencies bump

## Annotations module
- [x] libs reviewed
- [x] dependencies bump

## Traffic module
- [x] libs reviewed
- [x] dependencies bump

## Email module
- [x] libs reviewed
- [x] dependencies bump

## AEM Common
- [x] libs reviewed
- [x] dependencies bump

## AEM ClassicUI
- [x] libs reviewed
- [x] dependencies bump

## AEM TouchUI
- [x] libs reviewed
- [x] dependencies bump

## JUnit module
- [x] libs reviewed
- [x] dependencies bump

## Bobcumber module
- [x] libs reviewed
- [x] dependencies bump

## Core tests
- [x] libs reviewed
- [ ] dependencies bump

## Main project
- [x] libs reviewed
- [x] dependencies bump

**Comment by Shaihuludus** [comment]
Issues for each modules/libraries will be created and connected here

**Comment by mkrzyzanowski** [comment]
Still some dependencies are to be dealt with:
- `core` depends on `junit` and `cucumber` - this is due to the current state of the Loadable functionality (fixed with https://github.com/Cognifide/bobcat/pull/162/files, although we are considering deprecating and removing it: https://github.com/Cognifide/bobcat/pull/266)
- some of the dependencies will be removed in the next release

**Comment by mkrzyzanowski** [comment]
Released in `1.6.0`
