### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by discovermoi** [Cognifide/bobcat#246]
@mkrzyzanowski 

Guidance needed in supplying values to MULTIFIELD dialog field and its ITEMS in the below fashion.
Unclear of the Label and Third Parameter for the setField function to perform CLICK on the "Add field" button of MULTIFIELD.

Simialar guidance needed in using MULTIFIELD_ITEM dialog field to supply values field by field to the multifield sections.

![image](https://user-images.githubusercontent.com/26506371/40903082-5319a0ea-6815-11e8-94b7-f83d81762ed0.png)

**Comment by mkrzyzanowski** [comment]
Yeah, unfortunately, documentation lacks heavily in that area :disappointed: .

Please check out our AEM integration tests, I think you might find this particular test helpful: https://github.com/Cognifide/bobcat-aem-integration-tests/blob/11e29d7ef8589ebc1c188aaf82212d48d6ef18af/src/test/java/com/cognifide/bdd/demo/aem/touchui/AemCarouselTest.java#L95

**Comment by discovermoi** [comment]
All good. Thank you for this link.


________________________________

**Comment by discovermoi** [comment]
Resolved
