### ISSUE TITLE
I want to click on the inner parsys in the corner of the parsys. Is there any method to move the cursor?

### ISSUE THREAD

**Issue by thirunavookkarasu** [Cognifide/bobcat#247]
## Environment

Bobcat version:

Bobcat modules used:

* bb-aem-classic
* bb-aem-common
* bb-aem-touch-ui
* bb-annotations
* bb-core
* bb-cumber
* bb-email
* bb-junit
* bb-reports
* bb-traffic

Browser + version:

**Comment by mkrzyzanowski** [comment]
There is no such API at the moment. What you can do is extend the `Parsys` class ([link](https://github.com/Cognifide/bobcat/blob/fd14c7c535c7c8e9fb5664d87dfc3f8f446435e4/bb-aem-touch-ui/src/main/java/com/cognifide/qa/bb/aem/touch/pageobjects/touchui/Parsys.java)), then access the inner `WebElement`s and use them with `Actions` to move to a certain spot.
