### ISSUE TITLE
Is Bobcat supports AEM 6.3 ? Is there newer version of bobcat reelased to support AEM 6.3

### ISSUE THREAD

**Issue by thirunavookkarasu** [Cognifide/bobcat#248]
## Environment

Bobcat version:

Bobcat modules used:

* bb-aem-classic
* bb-aem-common
* bb-aem-touch-ui
* bb-annotations
* bb-core
* bb-cumber
* bb-email
* bb-junit
* bb-reports
* bb-traffic

Browser + version:

**Comment by mkrzyzanowski** [comment]
Please take a look at: https://github.com/Cognifide/bobcat/issues/229
