### ISSUE TITLE
bobcat framework - cucumber parallel plugin

### ISSUE THREAD

**Issue by sreedharsaravanan** [Cognifide/bobcat#249]
Request help to execute test in parallel.
I am using bobcat framework and added cucumber parallel plugin.
I am able to create multiple runner file based on tags.
When i execute -MVN test, i am seeing only 2 browser instance, but i have given 5.
Attaching my pom screen shot.
Request to let me know where i am wrong
<img width="1615" alt="screen shot 2018-06-25 at 11 52 09 am" src="https://user-images.githubusercontent.com/33815073/41869683-93801e0c-786e-11e8-8f77-2242eda2694a.png">
<img width="1189" alt="screen shot 2018-06-25 at 11 52 26 am" src="https://user-images.githubusercontent.com/33815073/41869687-97caa0f4-786e-11e8-9618-91f4762cd900.png">

**Comment by mkrzyzanowski** [comment]
Are you not overriding `forkCount` anywhere? Have you tried not reusing forks (i.e. `reuseForks=false`)?
In general, this is a problem related to Surefire configuration, please check: http://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html

**Comment by mkrzyzanowski** [comment]
Closing this for now, let us know in case of any further problems.
