### ISSUE TITLE
Inconsistent file structure for modules

### ISSUE THREAD

**Issue by basia-wulnikowska** [Cognifide/bobcat#255]
## Environment

Bobcat version:
1.4.1

## Expected Behavior
The SomeModule.java files for modules can be always found under similar path - my suggestion is to use an example of BobcumberModule: bb-cumber>src>main>java>com.cognifide.qa.bb>guice>BobcumberModule.java

## Actual Behavior
Inconsistent file structure for the modules. Some of them are placed in guice folder, some are directly in com.cognifide.qa.bb folder, some have other folder names. It's hard to find those files as every of them has other path to it.

## Description
Actual files structure:
* bb-aem-classic - ...\qa\bb\AemClassicModule.java
* bb-aem-common - ...qa\bb\aem\AemCommonModule.java
* bb-aem-touch-ui - ...\qa\bb\aem\touch\modules\AemTouchUiModule.java
* bb-core - ...\qa\bb\modules\CoreModule.java
* bb-cumber - ...\qa\bb\cumber\guice\BobcumberModule.java
* bb-email - ...\qa\bb\email\EmailModule.java
* bb-junit - x (not applicable)
* bb-reports - ...\qa\bb\logging\ReporterModule.java
* bb-traffic - ...\qa\bb\traffic\TrafficModule.java

**Comment by mkrzyzanowski** [comment]
Cleaned up (most of the modules were removed :))
