### ISSUE TITLE
Review CucumberJVM usage with JUnit 5 (and Allure)

### ISSUE THREAD

**Issue by mkrzyzanowski** [Cognifide/bobcat#271]
Since we are moving to JUnit 5, investigate how CucumberJVM is working with it.

Also, investigate if Allure can be easily hooked up with Cucumber.

**Comment by Shaihuludus** [comment]
Unfotunately this discussion is not optymistic:
https://github.com/cucumber/cucumber-jvm/issues/1149

As for now it is not possible to run cucumber using JUnit 5 (We can try to create engine using JUnit Engine mechanism)

**Comment by Shaihuludus** [comment]
Put in icebox until Cucumber will support JUnit5

**Comment by Shaihuludus** [comment]
As for now cucumber is not supportin junit5. There aren't currently plans for such support
