### ISSUE TITLE
Bump selenium version to latest with v1.5.0?

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat#272]
## Environment

Bobcat version:

Bobcat modules used:

* bb-aem-classic
* bb-aem-common
* bb-aem-touch-ui
* bb-annotations
* bb-core
* bb-cumber
* bb-email
* bb-junit
* bb-reports
* bb-traffic

Browser + version:

**Comment by mkrzyzanowski** [comment]
Selenium was upgraded in #270 and will be available with the next release.
