### ISSUE TITLE
How to configure gecko webdriver for Firefox browser

### ISSUE THREAD

**Issue by thirunavookkarasu** [Cognifide/bobcat#273]
## Environment

Bobcat version:
1.2.1

Bobcat modules used:
* bb-aem-touch-ui
* bb-core

Browser + version:  Firefox 59.0.3

Configuration Details:
Configured in webdriver.properties as follows
webdriver.type=firefox 
webdriver.gecko.driver=C:/webdrivers/firefox/geckodriver.exe
webdriver.firefox.bin=C:/mozilla/firefox.exe

## Expected Behavior:
Browser should open the author.url

## Actual Behavior
Throwing error message

**Comment by mkrzyzanowski** [comment]
Hi @thirunavookkarasu,

your configuration seems correct (also, you can include the location of your geckodriver executable in system's PATH, so it will be automatically picked up by Selenium). What error are you getting exactly? Please paste a complete stacktrace.

Oh, and I would recommend upgrading to the latest version, 1.5.0.

**Comment by mkrzyzanowski** [comment]
Closing for now, please let us know if the issue still persists.
