### ISSUE TITLE
Upgrade Cucumber Version

### ISSUE THREAD

**Issue by Shaihuludus** [Cognifide/bobcat#274]
The scope of this task is to upgrade Cucumber to the latest version (also check if such upgrade is possible)

**Comment by Shaihuludus** [comment]
Release notes:
Following changes are required in old tests:
In @CucumberOptions make sure that format is replaced with plugin
cucumber-guice.properties should be renamed to cucumber.properties

**Comment by Shaihuludus** [comment]
https://github.com/Cognifide/bobcat-gradle-template/pull/10 merge after release

**Comment by mkrzyzanowski** [comment]
Released in `1.6.0`
