### ISSUE TITLE
Upgrade Cucumber Version to 4.x

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat#309]
@kaczymuczy Cucumber ver 4.x allows us to run the test in parallel.
sample : https://github.com/abhishek8908/cucumber-v4-example

**Comment by DeChrish** [comment]
@mkrzyzanowski 
We are facing scoping issue while executing test in parallel and it was fixed in latest cucumber.
https://github.com/cucumber/cucumber-jvm/pull/1486

Pl add priority to this issue and support.

**Comment by mkrzyzanowski** [comment]
We're a bit short-handed at the moment so I can't give you any dates when we're going to implement it, but we will gladly review a pull request :)!

**Comment by DeChrish** [comment]
@mkrzyzanowski  Do we have regression test for pull request?

**Comment by mkrzyzanowski** [comment]
Hi!

We have finally addressed this but in a way that might be surprising to some of you - we have removed `bb-cumber` in the end and added Cucumber as a standalone dependency to our templates.

For rationale, general docs and migration steps please see: https://cognifide.github.io/bobcat/docs/cucumber/

**Comment by DeChrish** [comment]
@mkrzyzanowski  can we close this ticket?

**Comment by mkrzyzanowski** [comment]
Released in `2.1.0`
