### ISSUE TITLE
Failed to get allure-2.7.0.zip

### ISSUE THREAD

**Issue by adasongliang** [Cognifide/bobcat#312]
## Environment
Windows 7

Bobcat version:
How to know the version of bobcat.  I just clone it from github, suppose it's the latest verison. 

Bobcat modules used:
* bb-junit

Browser + version:
geckodriver-v0.23.0-win64

## Expected Behavior
N/A

## Actual Behavior
The error is printed in the command line as below: 
_______________________________________________________
* What went wrong:
Execution failed for task ':downloadAllure'.
> Can't get https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.7.0/allure-2.7.0.zip to E:\appium\bobcat-gradle-template\generated-project\build\allure-2.7.0.zip
_______________________________________________________

I tried to access above address directly via the browser, it shows forbidden. 
I want to know how to resolve this error. 

## Steps to reproduce
1. running the command "gradlew clean test" in Windows command line 

## More Info
This error won't impact the final test result report(index.html).
![image](https://user-images.githubusercontent.com/18712018/50435521-97ade100-091c-11e9-9c99-6e5c96e67e76.png)
But I still want to know what's wrong with my operation.  Anyone met the same issue?

**Comment by Shaihuludus** [comment]
Hi, there is probably problem with you firewall or network settings. Maybe your provider is blocking the site. I tried and there was no issues with downloading the zip file

**Comment by adasongliang** [comment]
If so, I will try again, thanks.
