### ISSUE TITLE
Bobcat 2.0 documentation fixes

### ISSUE THREAD

**Issue by blagne** [Cognifide/bobcat#316]
## Environment

Bobcat 2.0 documentation
published at https://cognifide.github.io/bobcat/

## Description
There are some broken links and other small mistakes in the Bobcat 2.0 documentation. They are listed below: 

### Issue 1 - link to _runmode_ is broken
**page URL:** https://cognifide.github.io/bobcat/docs/guides/first-aem-test/
**section:**  Writing your first AEM authoring test - Setup

EXPECTED:
https://cognifide.github.io/bobcat/docs/modules/core/runmodes/ 

ACTUAL:
https://cognifide.github.io/bobcatdocs/modules/core/runmodes/ 
user gets 404 Page Not Found

### Issue 2 - link to _Page Object_ is broken
**page URL:** https://cognifide.github.io/bobcat/docs/guides/first-test/
**section:**  Note in section _Our first Page Objects_
Note: if you would like to read more about working with Page Objects in Bobcat, check out the Working with Page Objects in Bobcat.

EXPECTED:
https://cognifide.github.io/bobcat/docs/modules/core/pageobject/ (I guess so)

ACTUAL:
https://cognifide.github.io/bobcat/docs/page-objects/ 
user gets 404

### Issue 3 - sentence difficult to understand
**page URL:** https://cognifide.github.io/bobcat/docs/modules/core/runmodes/
**section:** Overview
There is the sentence:
"With runmodes we can define that new runmode will use Aem64FullModule (when it will appear) not Aem64FullModule and module with different implementations. "

EXPECTED:
probably both Aem64FullModule and Aem65FullModule should be mentioned

ACTUAL:
Aem64FullModule mentioned twice - for me it does not explain runmodes clearly

### Issue 4 - grammar
**pageURL:**  https://cognifide.github.io/bobcat/docs/modules/core/waiting/
**secttion:** BobcatWait
sentence:  " This will your bread-and-butter when working with dynamic elements."

EXPECTED:
This will **be** your bread-and-butter when working with dynamic elements.

ACTUAL:
missing verb in the sentence

**Comment by mkrzyzanowski** [comment]
Fixed
