### ISSUE TITLE
Is bobcat framework is W3C compatible

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat#318]
## Environment

Bobcat version:

Bobcat modules used:

* bb-aem-classic
* bb-aem-common
* bb-aem-touch-ui
* bb-annotations
* bb-core
* bb-cumber
* bb-email
* bb-junit
* bb-reports
* bb-traffic

Browser + version:

**Comment by mkrzyzanowski** [comment]
Hi @DeChrish, do you mean are we W3C-WebDriver-spec compatible? We're currently using the `3.141.0` version of WebDriver and there are only very few places left were we used a deprecated API - the remaining deprecations will be removed in #314 (were we're going to bump Selenium version to the latest, too). As for W3C-spec compliance, it's mostly related to browser-specific implementations if they follow the spec :).

Hope that answers your question :).
