### ISSUE TITLE
AEM 6.4.2 Fix

### ISSUE THREAD

**Issue by Shaihuludus** [Cognifide/bobcat#321]
There are some markup changes (found in richtext) that stops authoring tests for that component. This can be found when running tests for 6.4 in https://github.com/Cognifide/bobcat-aem-tests

What should be done:

- [x] Create new module in bobcat for AEM 6.4.2 that will inherit from module 6.4 (new package should also be introduced)
- [x] Create new Guice Module for 6.4.2 
- [x] Validate which implementations has to be changed
- [x] Prepare new implementations and bind them in Guice in 6.4.2
- [x] Prepare tests https://github.com/Cognifide/bobcat-aem-tests for 6.4.2

Branch: https://github.com/Cognifide/bobcat/tree/64sp2

**Comment by mkrzyzanowski** [comment]
Done, to be released in `2.1.0`

**Comment by mkrzyzanowski** [comment]
After release, merge following: https://github.com/Cognifide/bobcat-aem-tests/pull/4

**Comment by GuptaMegha** [comment]
When is this 2.1.0 is going to be released?

**Comment by mkrzyzanowski** [comment]
Released in `2.1.0`
