### ISSUE TITLE
Bobcat ignoring explicitTimeout in config.yaml 

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat#328]
Config YML

default:
  properties:
    proxy.enabled: false
    proxy.ip: 127.0.0.1
    proxy.port: 9000
    timings.implicitTimeout: 1 # in seconds
    timings.explicitTimeout: 50 # in seconds
    timings.pollingInterval: 500 # in milliseconds
    page.title.timeout: 30
    allure.report: true
    allure.create.enviroment: true
  contexts: [chrome,locator,dev]

## Environment

Bobcat version:
6.4

Bobcat modules used:
* bb-core

Browser + version:
any

## Expected Behavior

Should have waited for 50 seconds

### 

Time elapsed: 44.613 s  <<< ERROR!
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of BobcatWebElement(Proxy element for: DefaultElementLocator 'By.cssSelector: #userid') (tried for 10 second(s) with 500 milliseconds interval)
Caused by: org.openqa.selenium.NoSuchElementException: 
no such element: Unable to locate element: {"method":"css selector","selector":"#userid"}

**Comment by DeChrish** [comment]
@mkrzyzanowski  if i pass from command line - it accepts the new timeout value; Pl guide

**Comment by DeChrish** [comment]
@Shaihuludus pl check what i wrong?

**Comment by mkrzyzanowski** [comment]
Hi @DeChrish,
indeed the properties are ignored 🤦‍♂. I'm going to fix this and include it in the next release (which may happen next week :)).

**Comment by GuptaMegha** [comment]
Hello, 
When is this going to be released?

**Comment by mkrzyzanowski** [comment]
Released in `2.1.0`
