### ISSUE TITLE
Sonatype security scan 

### ISSUE THREAD

**Issue by GuptaMegha** [Cognifide/bobcat#380]
Bobcat version:
2.1.0

## Description
There is critical security vulnerability discovered in the Sonatype scan for bobcat. Because of this security issue I can not use this framework for my AEM application.

## Expected Behavior
There should not be such higher security threat.

Is there anything that could be done, this will make the software secure.

**Comment by mkrzyzanowski** [comment]
Hi @GuptaMegha,

we've reviewed the remaining open issues, they were invalid in our case.

Bobcat is constantly checked by SonarCloud, you can see the results [here]( https://sonarcloud.io/dashboard?id=com.cognifide.qa.bb%3Abobcat)

**Comment by GuptaMegha** [comment]
Hi @mkrzyzanowski 

Please see attached sonatype report
[Bobcat-Build-20190910-140952.pdf](https://github.com/Cognifide/bobcat/files/3600051/Bobcat-Build-20190910-140952.pdf)
