### ISSUE TITLE
How to Override WebDriverProvider and Bind it with new create method?

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat#408]
Hi,
We would like to add logical condition to wait to create driver instance before VM;s are available in SauceLabs.

**some logic like below**
`  if (cachedWebDriver == null)
  {
while (retry) {
 if (suauceLabsVM !=0) {
 cachedWebDriver = create();
}
}
`

**Source file:**
https://github.com/Cognifide/bobcat/blob/master/bb-core/src/main/java/com/cognifide/qa/bb/provider/selenium/webdriver/WebDriverProvider.java

Override - SeleniumModule()

**Comment by mkrzyzanowski** [comment]
Since freshly released `2.2.0`, there is the `WebDriverCreator` mechanism available :).

Please check the following docs: https://cognifide.github.io/bobcat/docs/modules/core/webdriver/#custom-webdriver-creators

**Comment by DeChrish** [comment]
@mkrzyzanowski  Thanks. Pl plan monthly releases.
