### ISSUE TITLE
How to use  different CONTEXTS on RUNTIME 

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat#417]
How to use different contexts on runtime?

like, 
mvn clean test -Drunmode==<runmode_name> -Dcontexts=<browser_name>

**Comment by DeChrish** [comment]
mvn clean test -Dbobcat.config.contexts=chrome,ss007 ??

**Comment by Shaihuludus** [comment]
Hi,

"-D" is used to set system property in gradle not in maven

Please try to create maven profiles with required context and runmode values. Then use them in surefire plugin
http://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html

**Comment by DeChrish** [comment]
@Shaihuludus Thanks
