### ISSUE TITLE
TouchUI improvements - allow to configure single field

### ISSUE THREAD

**Issue by kkarolk** [Cognifide/bobcat#47]
Implementation of this issue enables to configure AEM TouchUI components field by field. There is no need to configure whole component from static, yaml-based configuration.

Example of Aem richtext component configuration using single dialog fields :
```Java
@Test
public void shouldRenderBoldedText() {

  //Assuming page is prepared earlier

  page.getParsys(parsys)
    .getComponent(COMPONENT_NAME)
    .openDialog()
    .setField("", FieldType.RICHTEXT.name(), "test test test")
    .setField("", FieldType.RICHTEXT_FONT_FORMAT.name(), "BOLD")
    .confirm();

     //Assertions here
}
```

**Comment by youngeagle87** [comment]
Implementation of this issue enables to configure AEM TouchUI components field by field. There is no need to configure whole component from static, yaml-based configuration.

Example of Aem richtext component configuration using single dialog fields :

```Java
@Test
public void shouldRenderBoldedText() {

  //Assuming page is prepared earlier

  page.getParsys(parsys)
    .getComponent(COMPONENT_NAME)
    .openDialog()
    .setField("", FieldType.RICHTEXT.name(), "test test test")
    .setField("", FieldType.RICHTEXT_FONT_FORMAT.name(), "BOLD")
    .confirm();

     //Assertions here
}
```

**Comment by discovermoi** [comment]
Hi kkarolK, I am using this field by field method to author components and working perfect unlike the 'configureComponent' method which feeds input values from a YAML file. It seldom works for me.

The issue with this setField is that, I am unable to use it for a checkbox. it works only for "false" value and not for "true" value. Any help on this would be highly appreciated. Thanks.

My statement is as follows:
.setField("",FieldType.CHECKBOX.name(),"true") - Third parameter with "true" value is not working

![image](https://user-images.githubusercontent.com/26506371/40465619-cd4fb772-5f60-11e8-89c8-914a01bf5752.png)

![image](https://user-images.githubusercontent.com/26506371/40465634-e0c74bee-5f60-11e8-983d-818fc919294c.png)

**Comment by discovermoi** [comment]
It is an application issue. The outer class of checkbox is coral-Form-fieldwrapper--singleline rather than coral-Form-fieldwrapper which is supported by the framework and hence closing it.

**Comment by discovermoi** [comment]
@kkarolk - Is it possible to configure MULTIFIELDs the same way? if so,What would the value of parameters "label" and "value" in the setField function to perform click action on the 
"Add field" button?

**Comment by kkarolk** [comment]
Hi,

Thanks for your email and sorry for not answering.
https://github.com/mkrzyzanowski will be the right person to ask your
questions as I'm not contributing to the project at the moment.

Cheers,
Kkarolk

pt., 1.06.2018, 09:59 użytkownik EM <notifications@github.com> napisał:
