### ISSUE TITLE
Research cucumber reporting as standalone reporting tool

### ISSUE THREAD

**Issue by kkarolk** [Cognifide/bobcat#83]
Currently we are using https://github.com/jenkinsci/cucumber-reports-plugin as reporting engine. It's fine, but has one disadvantage:  works only with jenkins CI. We would like to have a reporting engine which is CI independent. Research: https://github.com/damianszczepanik/cucumber-reporting.

**Comment by Shaihuludus** [comment]
As for now:

ReportGenerator from bb-cumber-reports module is calling report generation engine. 
In test project (bb-aem-integration-tests) there is class with main method that calls report generation from bobcat. Running this class should be done after tests in the same job

**Comment by mkrzyzanowski** [comment]
Reporting will be revamped, closing.
